### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by Glazelf** [StatsugiriGG/Statsugiri#140]
The README seems to still be for `Babiri.net`, which is down. Is there a live demo for `Statsugiri` and has the README just not been updated or is this still in the works?

**Comment by kelvinkoon** [comment]
A bit of both, unfortunately. 
I'm in the process of bringing the platform back, so the README has not been updated. It'll be a "belts and suspenders" solution first until I can flesh out a backend service since the competitive season is beginning soon. 
For updates, see Twitter (@StatsugiriGG) which is where I'll post production updates.
